export interface SystemTemplate {
  id:          string
  name:        string
  description: string
  category:    string
  isSystem:    true
  totalAmount: number
  usageCount:  number
  content:     Record<string, unknown>
  createdAt:   string
  updatedAt:   string
}

export const SYSTEM_TEMPLATES: SystemTemplate[] = [
  {
    id:          'system:web_design',
    name:        'Web Design & Development',
    description: 'Full website design and development — discovery, UI design, development, and launch.',
    category:    'Web Design',
    isSystem:    true,
    totalAmount: 88500,
    usageCount:  0,
    createdAt:   new Date(0).toISOString(),
    updatedAt:   new Date(0).toISOString(),
    content: {
      intro: 'Thank you for considering us for your website project. We specialize in building fast, modern websites that convert visitors into customers. This proposal outlines our approach, deliverables, and investment for your project.',
      whyUs: 'We have delivered 50+ websites for Indian businesses across e-commerce, services, and SaaS. Our process is structured, communication is transparent, and we deliver on time.',
      nextSteps: 'Review this proposal and let us know if you have any questions. Once accepted, we will schedule a kickoff call and share a project timeline.',
      scopeItems: [
        { title: 'Discovery & Planning', description: 'Kickoff call, sitemap finalization, competitor research, and project brief sign-off.' },
        { title: 'UI/UX Design', description: 'Wireframes for all key pages, high-fidelity Figma designs (desktop + mobile), and one round of revisions.' },
        { title: 'Development', description: 'Pixel-perfect implementation in React/Next.js with CMS integration, SEO meta tags, and performance optimization.' },
        { title: 'Testing & Launch', description: 'Cross-browser QA, mobile responsiveness testing, staging review, and live deployment.' },
      ],
      deliverables: [
        { item: 'Figma design files (all pages)', format: 'Figma' },
        { item: 'Fully functional website', format: 'Live URL' },
        { item: 'CMS setup with training', format: 'Recorded video' },
        { item: '30-day post-launch support', format: 'Email/WhatsApp' },
      ],
      exclusions: ['Domain and hosting costs', 'Third-party plugin licenses', 'Content writing or photography', 'Paid ad setup or SEO campaigns'],
      lineItems: [
        { description: 'UI/UX Design (up to 8 pages)', qty: 1, rate: 25000, gstRate: 18 },
        { description: 'Frontend Development',           qty: 1, rate: 40000, gstRate: 18 },
        { description: 'CMS Integration & Setup',        qty: 1, rate: 10000, gstRate: 18 },
      ],
      gstType: 'IGST',
      pricingNotes: 'Prices are exclusive of 18% GST. Hosting and domain renewal billed separately at actuals.',
      paymentSchedule: [
        { milestone: 'Project kickoff',      amount: 25000, dueOn: 'On agreement signing' },
        { milestone: 'Design approval',      amount: 25000, dueOn: 'After Figma sign-off' },
        { milestone: 'Development complete', amount: 25000, dueOn: 'Before launch' },
      ],
      milestones: [
        { title: 'Discovery & Design',  duration: '1 week',  description: 'Sitemap, wireframes, and high-fidelity designs' },
        { title: 'Development',         duration: '2 weeks', description: 'Full implementation and CMS setup' },
        { title: 'Testing & Launch',    duration: '3 days',  description: 'QA, feedback revisions, and go-live' },
      ],
      terms: `1. A 33% advance is required to commence work.\n2. Client to provide all content (text, images, logo) within 3 days of kickoff.\n3. Each phase includes one round of revisions. Additional revisions billed at ₹1,500/hour.\n4. Project timeline starts from receipt of advance and content.\n5. Unused revisions do not carry over to subsequent phases.\n6. Intellectual property transfers to client upon receipt of final payment.`,
    },
  },
  {
    id:          'system:brand_identity',
    name:        'Brand Identity Design',
    description: 'Logo, color palette, typography, and brand guidelines for a new or refreshed brand.',
    category:    'Branding',
    isSystem:    true,
    totalAmount: 35400,
    usageCount:  0,
    createdAt:   new Date(0).toISOString(),
    updatedAt:   new Date(0).toISOString(),
    content: {
      intro: 'A strong brand identity is the foundation of every successful business. This proposal covers the creation of a distinctive visual identity — from logo to brand guidelines — that will represent your business consistently across all touchpoints.',
      whyUs: 'We have built brand identities for 30+ startups and established businesses. Our strategic approach combines aesthetics with business positioning so your brand stands out and resonates with your target audience.',
      nextSteps: 'Once you accept this proposal, we will send a brand discovery questionnaire. Your responses inform our design direction, so the more detail you provide, the better the outcome.',
      scopeItems: [
        { title: 'Brand Discovery', description: 'Brand questionnaire, competitor visual audit, mood board creation, and design direction sign-off.' },
        { title: 'Logo Design', description: 'Three distinct logo concepts, followed by refinement of the chosen direction into a final logo suite (primary, secondary, icon).' },
        { title: 'Visual Identity System', description: 'Color palette, typography selection, iconography style, and pattern/texture elements.' },
        { title: 'Brand Guidelines Document', description: 'A comprehensive PDF guide covering logo usage rules, color codes, typography, and do/don\'t examples.' },
      ],
      deliverables: [
        { item: 'Final logo suite',           format: 'AI, EPS, SVG, PNG (all sizes)' },
        { item: 'Color palette',              format: 'HEX, RGB, CMYK values' },
        { item: 'Typography specification',   format: 'Font names + usage guide' },
        { item: 'Brand guidelines PDF',       format: '15–20 page PDF' },
        { item: 'Social media profile assets', format: 'PNG' },
      ],
      exclusions: ['Stationery or merchandise design', 'Website or app design', 'Social media content creation', 'Packaging design'],
      lineItems: [
        { description: 'Logo Design (3 concepts + refinement)', qty: 1, rate: 15000, gstRate: 18 },
        { description: 'Visual Identity System',                qty: 1, rate: 8000,  gstRate: 18 },
        { description: 'Brand Guidelines Document',             qty: 1, rate: 7000,  gstRate: 18 },
      ],
      gstType: 'IGST',
      pricingNotes: 'All prices are exclusive of 18% GST.',
      paymentSchedule: [
        { milestone: 'Project start',      amount: 15000, dueOn: 'On agreement signing' },
        { milestone: 'Logo approved',      amount: 15000, dueOn: 'After logo sign-off' },
      ],
      milestones: [
        { title: 'Discovery & Moodboards', duration: '3 days',  description: 'Questionnaire review, competitor audit, moodboard presentation' },
        { title: 'Logo Concepts',          duration: '5 days',  description: '3 concepts presented; 1 selected for refinement' },
        { title: 'Visual System',          duration: '3 days',  description: 'Color, typography, and supporting elements' },
        { title: 'Brand Guidelines',       duration: '3 days',  description: 'Complete guidelines document + asset handoff' },
      ],
      terms: `1. 50% advance required to start work.\n2. Three logo concepts presented; client selects one for refinement.\n3. Two rounds of revisions included. Additional revisions at ₹1,200/hour.\n4. All source files transferred upon receipt of final payment.\n5. Designer retains the right to showcase the work in portfolio (unless confidentiality clause requested).`,
    },
  },
  {
    id:          'system:social_media',
    name:        'Social Media Management',
    description: 'Monthly content creation, scheduling, and reporting for Instagram and LinkedIn.',
    category:    'Marketing',
    isSystem:    true,
    totalAmount: 14160,
    usageCount:  0,
    createdAt:   new Date(0).toISOString(),
    updatedAt:   new Date(0).toISOString(),
    content: {
      intro: 'Consistent, high-quality social media presence builds trust and drives inbound leads. This retainer covers everything needed to keep your brand active and growing on Instagram and LinkedIn every month.',
      whyUs: 'We manage social media for 15+ brands across D2C, services, and B2B sectors. Our content is strategy-led, not just aesthetically pleasing — every post serves a clear business objective.',
      nextSteps: 'Once accepted, we will onboard you with a brand voice questionnaire and a content approval workflow setup. Month 1 begins within 5 days of kickoff.',
      scopeItems: [
        { title: 'Monthly Strategy',      description: 'Content calendar for the month, theme planning, and hashtag research. Shared by the 28th of the previous month for approval.' },
        { title: 'Content Creation',      description: '12 posts per month (3/week): static graphics, carousels, and one Reel/short-form video per week. Copywriting included.' },
        { title: 'Scheduling & Posting',  description: 'All approved content scheduled and posted at optimal times using a scheduling tool. No manual effort required from your end.' },
        { title: 'Monthly Report',        description: 'End-of-month performance report covering reach, engagement rate, follower growth, and top-performing posts with insights.' },
      ],
      deliverables: [
        { item: 'Content calendar',    format: 'Google Sheet / Notion' },
        { item: '12 posts/month',      format: 'Instagram + LinkedIn' },
        { item: '4 Reels/short videos', format: 'MP4 (15–30 sec)' },
        { item: 'Monthly report',      format: 'PDF' },
      ],
      exclusions: ['Paid ad management', 'Influencer outreach', 'Photography or video production shoots', 'More than 2 revision rounds per post'],
      lineItems: [
        { description: 'Monthly Content Creation (12 posts + 4 Reels)', qty: 1, rate: 8000, gstRate: 18 },
        { description: 'Scheduling & Community Management',              qty: 1, rate: 2000, gstRate: 18 },
        { description: 'Strategy & Monthly Reporting',                   qty: 1, rate: 2000, gstRate: 18 },
      ],
      gstType: 'IGST',
      pricingNotes: 'This is a monthly retainer. Billed on the 1st of each month. Minimum commitment: 3 months.',
      paymentSchedule: [
        { milestone: 'Month 1 (advance)', amount: 12000, dueOn: 'On agreement signing' },
        { milestone: 'Month 2 onwards',   amount: 12000, dueOn: '1st of each month' },
      ],
      milestones: [
        { title: 'Onboarding',         duration: '2 days',   description: 'Brand voice questionnaire, content approval workflow setup' },
        { title: 'Content calendar',   duration: 'By 28th',  description: 'Next month\'s calendar shared for approval' },
        { title: 'Weekly posts',       duration: 'Weekly',   description: '3 posts + 1 Reel published per week' },
        { title: 'Monthly report',     duration: 'By 5th',   description: 'Previous month\'s performance review' },
      ],
      terms: `1. Minimum contract term: 3 months.\n2. 30-day written notice required to cancel.\n3. Client to provide brand assets (logo, product images) within 3 days of onboarding.\n4. Each post includes two rounds of revisions. Additional revisions at ₹500/post.\n5. Unused posts do not carry over to the next month.\n6. Client retains ownership of all published content.`,
    },
  },
  {
    id:          'system:photography',
    name:        'Photography Package',
    description: 'Professional photography for events, products, portraits, or commercial use.',
    category:    'Photography',
    isSystem:    true,
    totalAmount: 35400,
    usageCount:  0,
    createdAt:   new Date(0).toISOString(),
    updatedAt:   new Date(0).toISOString(),
    content: {
      intro: 'Thank you for considering us for your photography needs. We deliver high-quality, professionally edited images that capture your vision — whether it\'s a corporate event, product launch, or portrait session.',
      whyUs: 'We have 5+ years of experience shooting for Indian brands and individuals. Our editing turnaround is fast, our communication is clear, and we deliver print-ready and web-optimised files every time.',
      nextSteps: 'Review this proposal and confirm the date and location. We\'ll send a brief questionnaire to understand your vision, followed by an advance invoice to lock in the booking.',
      scopeItems: [
        { title: 'Pre-shoot Consultation',   description: 'Brief call or form to understand shot list, mood board, and location logistics.' },
        { title: 'On-location Shoot',        description: 'Full-day or half-day shoot as agreed, including setup and direction.' },
        { title: 'Culling & Selection',       description: 'Selection of the best shots from the session for editing.' },
        { title: 'Professional Editing',      description: 'Colour grading, retouching, and export in high-resolution JPEG + web-optimised versions.' },
        { title: 'Online Gallery Delivery',   description: 'Privately shared gallery link for download within the agreed turnaround.' },
      ],
      deliverables: [
        { item: 'High-resolution edited images',  format: 'JPEG (300 dpi)' },
        { item: 'Web-optimised versions',          format: 'JPEG (72 dpi)' },
        { item: 'Private online gallery',          format: 'Download link (30-day access)' },
      ],
      exclusions: ['Printing or physical albums', 'Video / videography', 'Hair, makeup, or styling', 'Location permit fees'],
      lineItems: [
        { description: 'Half-day Photography (4 hrs)', qty: 1, rate: 15000, gstRate: 18 },
        { description: 'Professional Editing (up to 50 images)', qty: 1, rate: 8000, gstRate: 18 },
        { description: 'Travel & Logistics',             qty: 1, rate: 2000, gstRate: 18 },
      ],
      gstType: 'IGST',
      pricingNotes: 'Prices exclude 18% GST. Additional hours billed at ₹3,500/hr.',
      paymentSchedule: [
        { milestone: 'Booking advance',      amount: 12500, dueOn: 'On agreement signing' },
        { milestone: 'Balance on delivery',  amount: 12500, dueOn: 'On gallery delivery' },
      ],
      milestones: [
        { title: 'Pre-shoot consultation', duration: '1–2 days before shoot', description: 'Shot list and location confirmed' },
        { title: 'Shoot day',              duration: 'As agreed',             description: 'On-location photography session' },
        { title: 'Delivery',               duration: '5–7 working days',      description: 'Edited gallery shared via private link' },
      ],
      terms: `1. A 50% advance is required to confirm the booking date.\n2. Cancellation within 48 hours of the shoot forfeits the advance.\n3. Rescheduling with 72+ hours notice is allowed once at no charge.\n4. Client is responsible for securing any required location permits.\n5. Final images are delivered in JPEG format only; RAW files are not shared.\n6. Copyright remains with the photographer; a non-exclusive usage licence is granted to the client.`,
    },
  },
  {
    id:          'system:video_production',
    name:        'Video Production',
    description: 'Corporate videos, brand films, reels, and testimonials — scripted, shot, and edited.',
    category:    'Video Production',
    isSystem:    true,
    totalAmount: 88500,
    usageCount:  0,
    createdAt:   new Date(0).toISOString(),
    updatedAt:   new Date(0).toISOString(),
    content: {
      intro: 'We craft compelling video content that builds your brand — from concept and scripting to shoot and final edit. Whether it\'s a 60-second brand film or a series of product reels, we handle it end to end.',
      whyUs: 'Our team has produced videos for 30+ Indian brands. We combine cinematic production quality with quick turnarounds and clear communication, so you\'re never guessing where your project stands.',
      nextSteps: 'Accept this proposal and we\'ll schedule a discovery call to lock in the concept, script direction, and shoot date. An advance invoice will follow to kick off pre-production.',
      scopeItems: [
        { title: 'Discovery & Scripting',     description: 'Brand questionnaire, concept development, and full script/storyboard for approval.' },
        { title: 'Pre-production',            description: 'Talent briefing, location scouting, shot list, and equipment planning.' },
        { title: 'Shoot Day',                 description: 'Full-day on-location or in-studio shoot with professional lighting and sound.' },
        { title: 'Post-production & Editing', description: 'Colour grading, audio mixing, motion graphics, subtitles, and two rounds of revisions.' },
        { title: 'Final Delivery',            description: 'Master file + compressed web versions (landscape, portrait, square formats).' },
      ],
      deliverables: [
        { item: 'Master video file',         format: 'MP4 (4K or 1080p)' },
        { item: 'Social media cuts',         format: 'MP4 (landscape + portrait + square)' },
        { item: 'Captioned/subtitled version', format: 'MP4' },
        { item: 'Raw footage archive',        format: 'On request only' },
      ],
      exclusions: ['Paid actors or professional models', 'Location permit fees', 'Music licensing (stock music included)', 'Animations beyond simple lower-thirds'],
      lineItems: [
        { description: 'Pre-production & Scripting',       qty: 1, rate: 15000, gstRate: 18 },
        { description: 'Full-day Shoot (crew + equipment)', qty: 1, rate: 35000, gstRate: 18 },
        { description: 'Post-production & Editing (1 video up to 3 min)', qty: 1, rate: 25000, gstRate: 18 },
      ],
      gstType: 'IGST',
      pricingNotes: 'Prices exclude 18% GST. Additional shoot days ₹25,000/day. Additional revision rounds ₹5,000 each.',
      paymentSchedule: [
        { milestone: 'Project kick-off',    amount: 25000, dueOn: 'On agreement signing' },
        { milestone: 'Post-production start', amount: 25000, dueOn: 'After shoot day' },
        { milestone: 'Final delivery',       amount: 25000, dueOn: 'On final file delivery' },
      ],
      milestones: [
        { title: 'Discovery & Script',  duration: '3–5 days',        description: 'Concept and script shared for approval' },
        { title: 'Pre-production',       duration: '3–5 days',        description: 'Shot list, talent brief, location confirmed' },
        { title: 'Shoot day',            duration: 'Day of shoot',    description: 'On-location/studio production' },
        { title: 'Rough cut',            duration: '5–7 working days', description: 'First edit shared for feedback' },
        { title: 'Final delivery',       duration: '3–5 working days', description: 'All final files delivered' },
      ],
      terms: `1. A 33% advance is required to begin pre-production.\n2. Client to provide brand guidelines, logo files, and any reference videos within 2 days of kick-off.\n3. Each video includes two rounds of revisions. Additional rounds billed at ₹5,000 each.\n4. Raw footage is not included unless separately agreed and billed.\n5. A usage licence is granted for the agreed platforms. Broadcast/paid media rights require a separate licence.\n6. IP transfers to client upon receipt of final payment.`,
    },
  },
  {
    id:          'system:interior_design',
    name:        'Interior Design Consultation',
    description: 'Space planning, mood boarding, material selection, and design execution for homes and offices.',
    category:    'Interior Design',
    isSystem:    true,
    totalAmount: 59000,
    usageCount:  0,
    createdAt:   new Date(0).toISOString(),
    updatedAt:   new Date(0).toISOString(),
    content: {
      intro: 'We transform spaces into functional, beautiful environments that reflect your personality and lifestyle. From concept to final styling, we handle every detail so you don\'t have to.',
      whyUs: 'With 8+ years of residential and commercial design experience across Indian cities, we understand local aesthetics, material availability, and vendor ecosystems — ensuring a smooth execution within your budget.',
      nextSteps: 'Accept this proposal and we\'ll schedule a site visit to take measurements and understand your vision. Work begins after the advance payment is received.',
      scopeItems: [
        { title: 'Site Visit & Briefing',   description: 'On-site measurement, photography, existing layout assessment, and detailed client brief.' },
        { title: 'Concept & Mood Board',    description: 'Two concept directions presented as mood boards (colour palette, materials, furniture style).' },
        { title: 'Space Planning',           description: 'AutoCAD 2D floor plan with furniture layout for all rooms in scope.' },
        { title: 'Material & Furniture Selection', description: 'Curated shortlist of materials, finishes, and furniture with vendor quotations.' },
        { title: 'Execution Support',        description: 'Vendor coordination, site visits during execution, and quality checks at key milestones.' },
      ],
      deliverables: [
        { item: '2D floor plan with furniture layout', format: 'PDF + AutoCAD' },
        { item: 'Mood board (approved concept)',        format: 'PDF' },
        { item: 'Material & finish schedule',           format: 'Excel / PDF' },
        { item: 'Vendor quotation tracker',             format: 'Excel' },
      ],
      exclusions: ['3D visualisation / renders (available as add-on)', 'Civil or structural work', 'Procurement / purchasing on behalf of client', 'Furniture or material costs'],
      lineItems: [
        { description: 'Design Consultation & Concept Development', qty: 1, rate: 20000, gstRate: 18 },
        { description: 'Space Planning (2D CAD drawings)',           qty: 1, rate: 15000, gstRate: 18 },
        { description: 'Execution Support (4 site visits)',          qty: 4, rate: 3000,  gstRate: 18 },
      ],
      gstType: 'IGST',
      pricingNotes: 'Design fees are fixed as above. Material and furniture costs are separate and paid directly by the client to vendors.',
      paymentSchedule: [
        { milestone: 'Project start',        amount: 20000, dueOn: 'On agreement signing' },
        { milestone: 'After concept approval', amount: 20000, dueOn: 'After mood board sign-off' },
        { milestone: 'Execution start',       amount: 19000, dueOn: 'Before site execution begins' },
      ],
      milestones: [
        { title: 'Site visit & brief',       duration: 'Day 1–3',   description: 'Measurement, photos, and client brief captured' },
        { title: 'Concept presentation',     duration: 'Day 7–10',  description: 'Mood boards and space plan presented' },
        { title: 'Material finalisation',    duration: 'Day 14–21', description: 'Materials, furniture, and vendor quotes approved' },
        { title: 'Execution & site support', duration: 'Per schedule', description: 'Weekly site visits during execution' },
      ],
      terms: `1. Design fees are payable as per the payment schedule regardless of execution timeline.\n2. Client is responsible for all procurement, material, and vendor payments directly.\n3. Each concept direction includes two rounds of revisions. Additional revisions billed at ₹3,000 each.\n4. Timeline estimates are indicative; delays due to vendor or civil work are not the designer's responsibility.\n5. The designer retains the right to use project photos for portfolio purposes (with client consent).\n6. Any changes to scope after sign-off will be billed separately.`,
    },
  },
  {
    id:          'system:consulting',
    name:        'Business Consulting Engagement',
    description: 'Strategy, operations, or process consulting — discovery, analysis, and actionable recommendations.',
    category:    'Consulting',
    isSystem:    true,
    totalAmount: 75000,
    usageCount:  0,
    createdAt:   new Date(0).toISOString(),
    updatedAt:   new Date(0).toISOString(),
    content: {
      intro: 'We partner with founders and business leaders to solve specific operational and strategic challenges — cutting through complexity to deliver clarity and a clear path forward.',
      whyUs: 'We bring cross-industry consulting experience across D2C, SaaS, and services businesses in India. Our engagements are outcome-focused, not hour-padded — you pay for results, not time on the clock.',
      nextSteps: 'Review this proposal and confirm the engagement scope. We\'ll schedule a kick-off session to align on goals, key stakeholders, and data access within the first week.',
      scopeItems: [
        { title: 'Discovery & Stakeholder Interviews', description: 'Structured interviews with key team members + review of existing data, processes, and documentation.' },
        { title: 'Current State Assessment',           description: 'Mapping of existing workflows, pain points, and gaps against business goals.' },
        { title: 'Analysis & Benchmarking',            description: 'Data analysis and benchmarking against industry peers where applicable.' },
        { title: 'Recommendations Report',             description: 'Prioritised, actionable recommendations with implementation roadmap and quick wins.' },
        { title: 'Presentation & Q&A',                 description: 'Executive presentation of findings and recommendation walkthrough with your team.' },
      ],
      deliverables: [
        { item: 'Current state assessment document', format: 'PDF' },
        { item: 'Recommendations report',            format: 'PDF + slide deck' },
        { item: 'Implementation roadmap',            format: 'Excel / PDF' },
        { item: 'Recorded presentation session',     format: 'Video link' },
      ],
      exclusions: ['Implementation or execution of recommendations', 'Software development or tooling', 'Ongoing operational support (available as a retainer)', 'Legal or financial advisory'],
      lineItems: [
        { description: 'Discovery & Assessment (week 1–2)',   qty: 1, rate: 25000, gstRate: 18 },
        { description: 'Analysis & Report Preparation (week 3)', qty: 1, rate: 30000, gstRate: 18 },
        { description: 'Presentation & Debrief Session',      qty: 1, rate: 8500,  gstRate: 18 },
      ],
      gstType: 'IGST',
      pricingNotes: 'Fixed-fee engagement. Travel expenses billed at actuals if on-site visits are required outside home city.',
      paymentSchedule: [
        { milestone: 'Engagement start',        amount: 37500, dueOn: 'On agreement signing' },
        { milestone: 'On delivery of report',   amount: 37500, dueOn: 'On report submission' },
      ],
      milestones: [
        { title: 'Kick-off & discovery',    duration: 'Week 1–2',   description: 'Stakeholder interviews and data collection' },
        { title: 'Analysis & drafting',      duration: 'Week 3',     description: 'Internal analysis and report drafting' },
        { title: 'Presentation & handover',  duration: 'Week 4',     description: 'Final report delivery and debrief session' },
      ],
      terms: `1. A 50% advance is required before the engagement begins.\n2. Client to provide timely access to relevant data, systems, and team members.\n3. All information shared by the client is treated as strictly confidential.\n4. Recommendations are advisory; the consultant is not liable for outcomes of implementation.\n5. The engagement scope is fixed. Additional scope items will be quoted separately.\n6. Either party may terminate the engagement with 7 days\' notice; work completed will be invoiced pro-rata.`,
    },
  },
]
