import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  NEW_RELIC_LICENSE_KEY: Joi.string().optional(),
  NEW_RELIC_APP_NAME: Joi.string().default('pakka-backend'),
  PORT: Joi.number().default(3000),
  DATABASE_URL: Joi.string().required(),
  SUPABASE_URL: Joi.string().uri().required(),
  SUPABASE_SERVICE_ROLE_KEY: Joi.string().required(),
  SUPABASE_JWT_SECRET: Joi.string().optional(),
  RAZORPAY_KEY_ID: Joi.string().required(),
  RAZORPAY_KEY_SECRET: Joi.string().required(),
  GEMINI_API_KEY: Joi.string().optional(),
  CORS_ORIGIN: Joi.string().required(),
  GOOGLE_CLIENT_ID:     Joi.string().optional(),
  GOOGLE_CLIENT_SECRET: Joi.string().optional(),
  GOOGLE_REDIRECT_URI:  Joi.string().optional(),
  MS_CLIENT_ID:         Joi.string().optional(),
  MS_CLIENT_SECRET:     Joi.string().optional(),
  MS_TENANT_ID:         Joi.string().default('common'),
  MS_REDIRECT_URI:      Joi.string().optional(),
  EMAIL_HOST: Joi.string().default('smtp.gmail.com'),
  EMAIL_PORT: Joi.number().default(587),
  EMAIL_USER: Joi.string().optional(),
  EMAIL_PASS: Joi.string().optional(),
  EMAIL_FROM: Joi.string().default('Rupway <noreply@rupway.in>'),
  APP_URL: Joi.string().default('http://localhost:5173'),
  VAPID_PUBLIC_KEY:  Joi.string().optional(),
  VAPID_PRIVATE_KEY: Joi.string().optional(),
  VAPID_SUBJECT:     Joi.string().default('mailto:noreply@rupway.in'),
});

export const configuration = () => ({
  port: parseInt(process.env.PORT ?? '3000', 10),
  nodeEnv: process.env.NODE_ENV,
  supabase: {
    url: process.env.SUPABASE_URL,
    serviceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY,
    jwtSecret: process.env.SUPABASE_JWT_SECRET,
  },
  razorpay: {
    keyId: process.env.RAZORPAY_KEY_ID,
    keySecret: process.env.RAZORPAY_KEY_SECRET,
  },
  google: {
    clientId:     process.env.GOOGLE_CLIENT_ID,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    redirectUri:  process.env.GOOGLE_REDIRECT_URI ?? 'http://localhost:3000/api/v1/auth/google/callback',
  },
  microsoft: {
    clientId:     process.env.MS_CLIENT_ID,
    clientSecret: process.env.MS_CLIENT_SECRET,
    tenantId:     process.env.MS_TENANT_ID ?? 'common',
    redirectUri:  process.env.MS_REDIRECT_URI ?? 'http://localhost:3000/api/v1/auth/microsoft/callback',
  },
  corsOrigin: process.env.CORS_ORIGIN,
  email: {
    host: process.env.EMAIL_HOST ?? 'smtp.gmail.com',
    port: parseInt(process.env.EMAIL_PORT ?? '587', 10),
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
    from: process.env.EMAIL_FROM ?? 'Rupway <noreply@rupway.in>',
  },
  appUrl: process.env.APP_URL ?? 'http://localhost:5173',
  geminiApiKey: process.env.GEMINI_API_KEY,
  newRelic: {
    licenseKey: process.env.NEW_RELIC_LICENSE_KEY,
    appName: process.env.NEW_RELIC_APP_NAME ?? 'pakka-backend',
  },
  webPush: {
    publicKey:  process.env.VAPID_PUBLIC_KEY,
    privateKey: process.env.VAPID_PRIVATE_KEY,
    subject:    process.env.VAPID_SUBJECT ?? 'mailto:noreply@rupway.in',
  },
});
