export interface DefaultRule {
  key:           string
  name:          string
  description:   string
  category:      string
  triggerEvent:  string
  triggerConfig: Record<string, unknown>
  actionType:    string
  actionConfig:  Record<string, unknown>
  isActive:      boolean
}

export const DEFAULT_AUTOMATION_RULES: DefaultRule[] = [
  // ── Invoice ──────────────────────────────────────────────────────────────
  {
    key:           'invoice.due_soon.d3',
    name:          'Invoice Due Soon – 3 Days',
    description:   'Sends a friendly heads-up to the client 3 days before an invoice is due.',
    category:      'invoice',
    triggerEvent:  'schedule.invoice.due_soon',
    triggerConfig: { days: 3 },
    actionType:    'send_email.client',
    actionConfig:  { templateKey: 'invoice_due_soon' },
    isActive:      true,
  },
  {
    key:           'invoice.overdue.d3',
    name:          'Invoice Overdue – Day 3',
    description:   'Sends a gentle payment reminder to the client 3 days after an invoice is overdue.',
    category:      'invoice',
    triggerEvent:  'schedule.invoice.overdue',
    triggerConfig: { days: 3 },
    actionType:    'send_email.client',
    actionConfig:  { templateKey: 'invoice_reminder_d3' },
    isActive:      true,
  },
  {
    key:           'invoice.overdue.d7',
    name:          'Invoice Overdue – Day 7',
    description:   'Sends a firmer payment reminder 7 days after an invoice is overdue.',
    category:      'invoice',
    triggerEvent:  'schedule.invoice.overdue',
    triggerConfig: { days: 7 },
    actionType:    'send_email.client',
    actionConfig:  { templateKey: 'invoice_reminder_d7' },
    isActive:      true,
  },
  {
    key:           'invoice.overdue.d14',
    name:          'Invoice Overdue – Final Notice',
    description:   'Sends a final payment notice 14 days after an invoice is overdue.',
    category:      'invoice',
    triggerEvent:  'schedule.invoice.overdue',
    triggerConfig: { days: 14 },
    actionType:    'send_email.client',
    actionConfig:  { templateKey: 'invoice_reminder_d14' },
    isActive:      true,
  },
  {
    key:           'invoice.paid',
    name:          'Thank-You on Payment',
    description:   'Sends a thank-you email to the client the moment their payment is confirmed.',
    category:      'invoice',
    triggerEvent:  'event.invoice.paid',
    triggerConfig: {},
    actionType:    'send_email.client',
    actionConfig:  { templateKey: 'invoice_paid_thanks' },
    isActive:      true,
  },

  // ── Proposal ─────────────────────────────────────────────────────────────
  {
    key:           'proposal.accepted',
    name:          'Proposal Accepted → Auto-Create Contract',
    description:   'Automatically creates a contract draft when a proposal is accepted.',
    category:      'proposal',
    triggerEvent:  'event.proposal.accepted',
    triggerConfig: {},
    actionType:    'create.contract',
    actionConfig:  {},
    isActive:      true,
  },
  {
    key:           'proposal.not_opened.d3',
    name:          'Proposal Not Opened – 3 Days',
    description:   'Alerts you if a client hasn\'t opened your proposal after 3 days.',
    category:      'proposal',
    triggerEvent:  'schedule.proposal.not_opened',
    triggerConfig: { days: 3 },
    actionType:    'send_email.user',
    actionConfig:  { templateKey: 'proposal_not_opened_alert' },
    isActive:      true,
  },
  {
    key:           'proposal.opened.no_response.d2',
    name:          'Proposal Viewed – No Response (2 Days)',
    description:   'Alerts you when a client viewed your proposal but hasn\'t responded after 2 days.',
    category:      'proposal',
    triggerEvent:  'schedule.proposal.opened_no_response',
    triggerConfig: { days: 2 },
    actionType:    'send_email.user',
    actionConfig:  { templateKey: 'proposal_viewed_alert' },
    isActive:      true,
  },
  {
    key:           'proposal.expiring.d1',
    name:          'Proposal Expiring Tomorrow',
    description:   'Reminds the client that their proposal expires in 24 hours.',
    category:      'proposal',
    triggerEvent:  'schedule.proposal.expiring',
    triggerConfig: { days: 1 },
    actionType:    'send_email.client',
    actionConfig:  { templateKey: 'proposal_expiry_notice' },
    isActive:      true,
  },

  // ── Contract ─────────────────────────────────────────────────────────────
  {
    key:           'contract.signed',
    name:          'Contract Signed → Auto-Create Invoice',
    description:   'Automatically creates an invoice draft when a contract is signed.',
    category:      'contract',
    triggerEvent:  'event.contract.signed',
    triggerConfig: {},
    actionType:    'create.invoice',
    actionConfig:  {},
    isActive:      true,
  },
  {
    key:           'contract.not_signed.d3',
    name:          'Contract Not Signed – 3 Days',
    description:   'Sends a reminder to the client to sign the contract after 3 days.',
    category:      'contract',
    triggerEvent:  'schedule.contract.not_signed',
    triggerConfig: { days: 3 },
    actionType:    'send_email.client',
    actionConfig:  { templateKey: 'contract_reminder_d3' },
    isActive:      true,
  },
  {
    key:           'contract.not_signed.d7',
    name:          'Contract Not Signed – 7 Days',
    description:   'Sends a follow-up reminder to sign the contract after 7 days.',
    category:      'contract',
    triggerEvent:  'schedule.contract.not_signed',
    triggerConfig: { days: 7 },
    actionType:    'send_email.client',
    actionConfig:  { templateKey: 'contract_reminder_d7' },
    isActive:      true,
  },

  // ── Lead ─────────────────────────────────────────────────────────────────
  {
    key:           'lead.cold.d7',
    name:          'Cold Lead Alert – 7 Days',
    description:   'Alerts you when a lead has had no activity for 7 days.',
    category:      'lead',
    triggerEvent:  'schedule.lead.cold',
    triggerConfig: { days: 7 },
    actionType:    'send_email.user',
    actionConfig:  { templateKey: 'lead_cold_alert' },
    isActive:      true,
  },
  {
    key:           'lead.created',
    name:          'New Enquiry Auto-Reply',
    description:   'Automatically replies to a new lead\'s email to acknowledge their enquiry.',
    category:      'lead',
    triggerEvent:  'event.lead.created',
    triggerConfig: {},
    actionType:    'send_email.client',
    actionConfig:  { templateKey: 'lead_new_enquiry' },
    isActive:      false,
  },

  // ── Business ─────────────────────────────────────────────────────────────
  {
    key:           'business.gst_reminder',
    name:          'GST Filing Reminder',
    description:   'Reminds you to file GSTR-1 on the 8th of every month.',
    category:      'business',
    triggerEvent:  'schedule.calendar',
    triggerConfig: { cron: '0 9 8 * *' },
    actionType:    'send_email.user',
    actionConfig:  { templateKey: 'gst_reminder' },
    isActive:      true,
  },
  {
    key:           'business.weekly_digest',
    name:          'Weekly Business Digest',
    description:   'Sends you a pipeline snapshot every Monday morning.',
    category:      'business',
    triggerEvent:  'schedule.calendar',
    triggerConfig: { cron: '0 9 * * 1' },
    actionType:    'send_email.user',
    actionConfig:  { templateKey: 'weekly_digest' },
    isActive:      true,
  },
  {
    key:           'business.monthly_summary',
    name:          'Monthly Revenue Summary',
    description:   'Sends a monthly revenue and pipeline summary on the 1st of each month.',
    category:      'business',
    triggerEvent:  'schedule.calendar',
    triggerConfig: { cron: '0 9 1 * *' },
    actionType:    'send_email.user',
    actionConfig:  { templateKey: 'monthly_summary' },
    isActive:      false,
  },

  // ── WhatsApp (all off by default — owner must connect WABA and enable per-event) ─
  // TODO(WhatsApp): These rules are seeded with isActive: false. To activate:
  //   1. Owner connects WhatsApp via Settings → Communication → Connect WhatsApp
  //   2. Owner toggles desired events on in the toggle grid
  //   3. ClearWork Meta App must be registered and templates approved
  {
    key:           'wa.proposal.sent',
    name:          'WhatsApp — Proposal Shared',
    description:   'Sends a WhatsApp notification to the client when a proposal is shared.',
    category:      'whatsapp',
    triggerEvent:  'event.proposal.sent',
    triggerConfig: {},
    actionType:    'send_whatsapp.client',
    actionConfig:  { templateKey: 'wa_proposal_shared' },
    isActive:      false,
  },
  {
    key:           'wa.contract.sent',
    name:          'WhatsApp — Contract Sent',
    description:   'Sends a WhatsApp notification to the client when a contract is sent for signing.',
    category:      'whatsapp',
    triggerEvent:  'event.contract.sent',
    triggerConfig: {},
    actionType:    'send_whatsapp.client',
    actionConfig:  { templateKey: 'wa_contract_sent' },
    isActive:      false,
  },
  {
    key:           'wa.contract.signed',
    name:          'WhatsApp — Contract Signed',
    description:   'Sends a WhatsApp confirmation to the client when they sign a contract.',
    category:      'whatsapp',
    triggerEvent:  'event.contract.signed',
    triggerConfig: {},
    actionType:    'send_whatsapp.client',
    actionConfig:  { templateKey: 'wa_contract_signed' },
    isActive:      false,
  },
  {
    key:           'wa.invoice.sent',
    name:          'WhatsApp — Invoice Sent',
    description:   'Sends a WhatsApp notification to the client when an invoice is sent.',
    category:      'whatsapp',
    triggerEvent:  'event.invoice.sent',
    triggerConfig: {},
    actionType:    'send_whatsapp.client',
    actionConfig:  { templateKey: 'wa_invoice_sent' },
    isActive:      false,
  },
  {
    key:           'wa.invoice.due_soon',
    name:          'WhatsApp — Payment Reminder',
    description:   'Sends a WhatsApp payment reminder to the client when an invoice is due soon.',
    category:      'whatsapp',
    triggerEvent:  'schedule.invoice.due_soon',
    triggerConfig: { days: 3 },
    actionType:    'send_whatsapp.client',
    actionConfig:  { templateKey: 'wa_payment_reminder' },
    isActive:      false,
  },
  {
    key:           'wa.invoice.paid',
    name:          'WhatsApp — Payment Received',
    description:   'Sends a WhatsApp thank-you to the client when payment is confirmed.',
    category:      'whatsapp',
    triggerEvent:  'event.invoice.paid',
    triggerConfig: {},
    actionType:    'send_whatsapp.client',
    actionConfig:  { templateKey: 'wa_payment_received' },
    isActive:      false,
  },
  {
    key:           'wa.project.completed',
    name:          'WhatsApp — Project Completed',
    description:   'Sends a WhatsApp message to the client when a project is marked as completed.',
    category:      'whatsapp',
    triggerEvent:  'event.project.completed',
    triggerConfig: {},
    actionType:    'send_whatsapp.client',
    actionConfig:  { templateKey: 'wa_project_completed' },
    isActive:      false,
  },
]
